### PR TITLE
Docs: Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by Arsenic-ATG**
The changes include : 
- [x] Add basic info to the contribution guidelines
- [x] Add **Before you begin** section for prerequisites.
- [x] Add sections about Issues
- [x] Add section for PR and workflow
- [x] Add additional resources for beginners
- [x] Add table of content.

### CODE REVIEW

**Review by HimeshNayak — APPROVED** [review]
LGTM 💯

**Comment by Arsenic-ATG** [comment]
The changes still need some fine tuning and commits need some cleaning, so marking this PR as draft for now.

**Review by HimeshNayak — APPROVED** [review]
LGr8TM 💯

**Review by RGTechno — APPROVED** [review]
LGTM

**Comment by RGTechno** [comment]
> LGTM

Merging it into master

**Pull request merged**
